"""empty message

Revision ID: bc96bf62472d
Revises: 256ec82f139d
Create Date: 2020-12-08 00:34:42.232960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc96bf62472d'
down_revision = '256ec82f139d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tablero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('todo', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('tablero')
    # ### end Alembic commands ###
